export enum Credentials {
  API_URL='https://ybdklqxalbyudmcxcfhy.supabase.co/rest/v1/',
  API_KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliZGtscXhhbGJ5dWRtY3hjZmh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjU4NTQxNzcsImV4cCI6MTk4MTQzMDE3N30.rpkoMO_EkNyhu4l2cNZ3IIMBy8pkYUH5buonAdq9AP4'
}
